### ISSUE TITLE
Car Rental for Customer App

### ISSUE THREAD

**Issue by Dara-Mapping** [Dara-Mapping/autospace#1]
Research Customer Apps for car rental

I. Draw Process flow high-level (features or functionalities)
2. How to generate income (What is the feature that can create income)
 

II. Draw Process flow in more detail (feature or functionalities)
2. How to generate income  (What is the feature that can create income)

**Comment by ChuonMao** [comment]
![Image](https://github.com/user-attachments/assets/53972bdb-7844-4122-8c9e-7757fc7d946c)

**Comment by ChuonMao** [comment]
![Image](https://github.com/user-attachments/assets/95f76600-7b29-4dee-a941-a72451c492cb)

**Comment by ChuonMao** [comment]
[Car rental features Details-High level process flow car rental.drawio (1).pdf](https://github.com/user-attachments/files/17023203/Car.rental.features.Details-High.level.process.flow.car.rental.drawio.1.pdf)

**Comment by ChuonMao** [comment]
![photo_2024-09-17_12-18-17](https://github.com/user-attachments/assets/9444346c-9a31-457e-9422-621f25752d98)

**Comment by ChuonMao** [comment]
https://app.diagrams.net/#G1_fz_kt6AFBlxlRiz8UYm9yRmDtDP-AbN#%7B%22pageId%22%3A%22gyuY4oPyMsQSlljEGBdK%22%7D
