### ISSUE TITLE
Insurance (host)

### ISSUE THREAD

**Issue by satmekh** [Dara-Mapping/autospace#11]
1. create insurance screen
link draw.io (https://app.diagrams.net/#G1kvYRZ0I06bwrFHPxLrk48P8RuV-hTLHh#%7B%22pageId%22%3A%22w1hNrXyAHTFI8Z28a2kt%22%7D)
![Image](https://github.com/user-attachments/assets/b61634d9-e0f3-4303-9c72-ba4819c299ab)

**Comment by satmekh** [comment]
1.Add Insurance

**Comment by Dara-Mapping** [comment]
Pls change word "insurance license" to insurance certification"

**Comment by Dara-Mapping** [comment]
![Image](https://github.com/user-attachments/assets/b02d446c-1f36-416a-b32d-e4e32fdde4bc)

We should mention Ex. insurance companies that cooperate with our business and more rating 1.5% per year but they have the option to choose (minimum 1 month)

**Comment by satmekh** [comment]
> ![Image](https://github.com/user-attachments/assets/b02d446c-1f36-416a-b32d-e4e32fdde4bc)
> 
> We should mention Ex. insurance companies that cooperate with our business and more rating 1.5% per year but they have the option to choose (minimum 1 month)

![Image](https://github.com/user-attachments/assets/0434c12e-c0bc-4498-9eef-c09f8f7c42ae)
I updated

**Comment by satmekh** [comment]
reminder add contact number

**Comment by Dara-Mapping** [comment]
Hi Mekh,

**Comment by satmekh** [comment]
Updated 
![Image](https://github.com/user-attachments/assets/380bbd90-9607-4145-a3d3-afa13294660d)
