### ISSUE TITLE
Rate trip (host)

### ISSUE THREAD

**Issue by satmekh** [Dara-Mapping/autospace#12]
1. Create screen rate trip
link draw.io(https://app.diagrams.net/#G1kvYRZ0I06bwrFHPxLrk48P8RuV-hTLHh#%7B%22pageId%22%3A%22w1hNrXyAHTFI8Z28a2kt%22%7D)
![Image](https://github.com/user-attachments/assets/6b790338-b715-403b-a014-4a7de9f6586e)

**Comment by Dara-Mapping** [comment]
Hi Mekh, Please note the limitation of the character number for example 300 words.

**Comment by satmekh** [comment]
> Hi Mekh, Please note the limitation of the character number for example 300 words on message rating writing .

I updated the limitation of the character number on message rating writing 

![Image](https://github.com/user-attachments/assets/16c07855-2ac7-487b-a08d-dea033cdeace)
