### ISSUE TITLE
Report issue (host)

### ISSUE THREAD

**Issue by satmekh** [Dara-Mapping/autospace#13]
**Report an issue**
1.Smoking violation
2.Cleaning violation
3.Late return (vehicle not return)
4.late return  ( vehicle return)

link https://app.diagrams.net/#G1kvYRZ0I06bwrFHPxLrk48P8RuV-hTLHh#%7B%22pageId%22%3A%22w1hNrXyAHTFI8Z28a2kt%22%7D

**Comment by satmekh** [comment]
1.![Image](https://github.com/user-attachments/assets/80bddc0e-0ec5-4c1a-8caf-3cd857afcbc1)
2.![Image](https://github.com/user-attachments/assets/988c69f6-c002-418d-8c67-5f1a20f8b649)
3. ![Image](https://github.com/user-attachments/assets/2aa087fa-526f-43db-a420-ffe2395dc80b)

**Comment by Dara-Mapping** [comment]
Hi Mekh,
please help to explain me more about the rule of fee change for late return.

![Image](https://github.com/user-attachments/assets/a198cf19-0e3c-4487-b811-d866a867e021)

**Comment by satmekh** [comment]
> Hi Mekh, please help to explain me more about the rule of fee change for late return.
> 
> ![Image](https://github.com/user-attachments/assets/a198cf19-0e3c-4487-b811-d866a867e021)

It no connect with trip buffer refers to a situation where the guest returns the vehicle after the scheduled end time of the trip late.

**Comment by satmekh** [comment]
what process of flow report issue goes to?
