### ISSUE TITLE
Process flow of listing cars rental as a host

### ISSUE THREAD

**Issue by satmekh** [Dara-Mapping/autospace#17]
![Image](https://github.com/user-attachments/assets/57294cb4-55bc-4549-bfa3-06a9acaf74cb)

**Comment by satmekh** [comment]
https://drive.google.com/file/d/1hX2NvCLA71MQPjgp9ly4tFa8dRKt9NNS/view?usp=sharing

![Image](https://github.com/user-attachments/assets/3bd4078e-3122-4689-8823-b89d0a12f83d)

**Comment by Dara-Mapping** [comment]
Hi Mekh,

Please modify this process flow  to add on more process 

![Image](https://github.com/user-attachments/assets/90af5f4f-8070-46a2-a8fe-68d2290b3753)

1. Registration 
2. Verification

**Comment by satmekh** [comment]
Updated
![Image](https://github.com/user-attachments/assets/533cfc6d-550d-473d-8417-e5a06747b713)
