### ISSUE TITLE
Recieve Report Damage for Guest

### ISSUE THREAD

**Issue by Dara-Mapping** [Dara-Mapping/autospace#3]

**Comment by ChuonMao** [comment]
Note: 
+ case when this button show Modify trip :

 -  required license photo
 - Host-Requested Changes
 - change the pickup or return location
+ if guest and host no request change everything  good, this button it show Cancel trip

**Comment by Dara-Mapping** [comment]
Please provide link draw.oi.

**Comment by ChuonMao** [comment]
https://app.diagrams.net/#G1745tPTI4XeUbm8s1QzLI6jVaIwyZx_Ts#%7B%22pageId%22%3A%226ldpYIiZnnuh16e5r1d4%22%7D

![Image](https://github.com/user-attachments/assets/348877fe-5139-4a7e-9b96-787ecc0da0b4)

**Comment by Dara-Mapping** [comment]
Pls consider again on the "Modify Trip" button.
When does it show?
