### ISSUE TITLE
 Report Damages Host

### ISSUE THREAD

**Issue by satmekh** [Dara-Mapping/autospace#4]

**Comment by satmekh** [comment]
Link draw.io (https://drive.google.com/file/d/1EAfSdXtDrJHA1peet7ehNoK4ZndDNawO/view?usp=drive_link)
1.Report damage
2.Heads up
3.Select damage type
4.Select damage type

**Comment by satmekh** [comment]
1. Update map
2. Update Form

**Comment by Dara-Mapping** [comment]
Hi  Mekh, 
I thought the report was physical damage, but it's fine. How about the mechanical damage?
we should research more.

![Image](https://github.com/user-attachments/assets/29022025-4a97-4c4c-a048-71e8b1f06f2c)

**Comment by satmekh** [comment]
> Hi Mekh, I thought the report was physical damage, but it's fine. How about the mechanical damage? we should research more.
> 
> ![Image](https://github.com/user-attachments/assets/29022025-4a97-4c4c-a048-71e8b1f06f2c)

There is no other form for mechanical damage. We use the same for physical damage. It just a question ask to know what type of damage.

**Comment by satmekh** [comment]
> > Hi Mekh, I thought the report was physical damage, but it's fine. How about the mechanical damage? we should research more.
> > ![Image](https://github.com/user-attachments/assets/29022025-4a97-4c4c-a048-71e8b1f06f2c)
> 
> There is no other form for mechanical damage. We use the same for physical damage. It just a question ask to know what type of damage.

It is multi check box there is no other form due to mechanical is not the like physical damage so that's why it can set form specific like physical damage. ![Image](https://github.com/user-attachments/assets/0ff32c7a-4e34-4c47-92b0-c716aae6b88e)

**Comment by Dara-Mapping** [comment]
pls change the icon circle to a square 

![Image](https://github.com/user-attachments/assets/98b7f36b-3cc8-4b92-ba50-52c5f5ae6614)

**Comment by satmekh** [comment]
> pls change the icon circle to a square
> 
> ![Image](https://github.com/user-attachments/assets/98b7f36b-3cc8-4b92-ba50-52c5f5ae6614)

![Image](https://github.com/user-attachments/assets/9f148c77-330f-41cc-833d-7e0d6fc8f503)
