### ISSUE TITLE
summery process flow booking car rental app (Guest)

### ISSUE THREAD

**Issue by Dara-Mapping** [Dara-Mapping/autospace#9]
summery process flow booking car rental app (Guest)

**Comment by ChuonMao** [comment]
https://app.diagrams.net/#G1745tPTI4XeUbm8s1QzLI6jVaIwyZx_Ts#%7B%22pageId%22%3A%220bsV4-2jTeAuYMe-CJfk%22%7D

**Comment by Dara-Mapping** [comment]
Ok, good move.
